# Generated by Django 5.1.2 on 2024-11-23 12:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventoApp", "0002_alter_item_model_height_cm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movement",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Purchase Price",
            ),
        ),
        migrations.AlterField(
            model_name="movement",
            name="sale_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Sale Price",
            ),
        ),
    ]
