# Generated by Django 5.1.2 on 2024-11-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoApp', '0003_alter_movement_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_model',
            name='unit_measure',
            field=models.CharField(choices=[('units', 'Units (pcs)'), ('packs', 'Packs (pks)'), ('sets', 'Sets'), ('cases', 'Cases (cs)'), ('boxes', 'Boxes (bx)'), ('kilograms', 'Kilograms (kg)'), ('meters', 'Meters (m)'), ('liters', 'Liters (l)')], max_length=20),
        ),
    ]
